name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - run: nix build .#firmware
      - uses: actions/upload-artifact@v4
        with:
          name: zmk_firmware
          path: result
